# Configuração do banco de dados H2 (modo arquivo)
spring.datasource.url=jdbc:h2:file:./data/registrodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Timezone
spring.jackson.time-zone=America/Sao_Paulo

# JWT Configuration
jwt.secret=a2V5c2VjcmV0YWRlYXV0ZW50aWNhY2FvcGFyYWdlcmFydG9rZW5zand0c2VjcmV0YWRlYXV0ZW50aWNhY2FvcGFyYWdlcmFydG9rZW5zand0
jwt.expiration=86400